# Copyright (c) Facebook, Inc. and its affiliates.
from .config import CfgNode as CN

# NOTE: given the new config system
# (https://detectron2.readthedocs.io/en/latest/tutorials/lazyconfigs.html),
# we will stop adding new functionalities to default CfgNode.

# -----------------------------------------------------------------------------
# Convention about Training / Test specific parameters
# -----------------------------------------------------------------------------
# Whenever an argument can be either used for training or for testing, the
# corresponding name will be post-fixed by a _TRAIN for a training parameter,
# or _TEST for a test-specific parameter.
# For example, the number of images during training will be
# IMAGES_PER_BATCH_TRAIN, while the number of images for testing will be
# IMAGES_PER_BATCH_TEST

# -----------------------------------------------------------------------------
# Config definition
# -----------------------------------------------------------------------------

_C = CN()

_C.DEBUG = False
_C.OUTPUT_DIR = ""
_C.SEED = 3407
_C.DETERMINISTIC = True
_C.RESUME_CKPT_PATH = None
_C.PRETRAINED_CKPT_PATH = None
_C.EXPERIMENTAL_TYPE = "simulation"       # simulation | real


_C.DATASETS = CN()
_C.DATASETS.STEP = 2
_C.DATASETS.WAVE_LENS = 28
_C.DATASETS.MASK_TYPE = "mask_3d"
_C.DATASETS.WITH_PAN = True

_C.DATASETS.TRAIN = CN()
_C.DATASETS.TRAIN.MASK_PATH = ""
_C.DATASETS.TRAIN.RANDOM_MASK = False 
_C.DATASETS.TRAIN.PATHS = []
_C.DATASETS.TRAIN.ITERATION = 1000
_C.DATASETS.TRAIN.CROP_SIZE = [256, 256]
_C.DATASETS.TRAIN.AUGMENT = True
_C.DATASETS.TRAIN.WITH_NOISE = False


_C.DATASETS.VAL = CN()
_C.DATASETS.VAL.MASK_PATH = ""
_C.DATASETS.VAL.PATH = ""

_C.DATASETS.VAL_INDOOR = CN()
_C.DATASETS.VAL_INDOOR.MASK_PATH = ""
_C.DATASETS.VAL_INDOOR.PATH = ""

_C.DATASETS.VAL_OUTDOOR = CN()
_C.DATASETS.VAL_OUTDOOR.MASK_PATH = ""
_C.DATASETS.VAL_OUTDOOR.PATH = ""


_C.DATASETS.TEST = CN()
_C.DATASETS.TEST.PATH = ""
_C.DATASETS.TEST.MASK_PATH = ""


_C.DATASETS.TEST_INDOOR = CN()
_C.DATASETS.TEST_INDOOR.PATH = ""
_C.DATASETS.TEST_INDOOR.MASK_PATH = ""

_C.DATASETS.TEST_OUTDOOR = CN()
_C.DATASETS.TEST_OUTDOOR.PATH = ""
_C.DATASETS.TEST_OUTDOOR.MASK_PATH = ""


# DATALOADER
_C.DATALOADER = CN()
_C.DATALOADER.BATCH_SIZE = 4
_C.DATALOADER.NUM_WORKERS = 8
_C.DATALOADER.PIN_MEMORY = False


# MODEL
_C.MODEL = CN()
_C.MODEL.TYPE = "MST"
_C.MODEL.EMA = False

# MST
_C.MODEL.MST = CN()
_C.MODEL.MST.DIM = 28
_C.MODEL.MST.STAGE = 3
_C.MODEL.MST.NUM_BLOCKS = [2, 2, 2]

# DGSMP
_C.MODEL.DGSMP = CN()
_C.MODEL.DGSMP.CH = 28
_C.MODEL.DGSMP.STAGES = 4

# TSA_Net
_C.MODEL.TSA_NET = CN()
_C.MODEL.TSA_NET.IN_CH = 28
_C.MODEL.TSA_NET.OUT_CH = 28


# DAUHST
_C.MODEL.DAUHST = CN()
_C.MODEL.DAUHST.STAGES = 9
_C.MODEL.DAUHST.WINDOW_SIZE = [8, 8]

# RDLUF_MixS2
_C.MODEL.RDLUF_MIXS2 = CN()
_C.MODEL.RDLUF_MIXS2.STAGES = 9
_C.MODEL.RDLUF_MIXS2.BODY_SHARE_PARAMS = True
_C.MODEL.RDLUF_MIXS2.ACT_FN_NAME = "gelu"
_C.MODEL.RDLUF_MIXS2.BIAS = False
_C.MODEL.RDLUF_MIXS2.IN_DIM = 28
_C.MODEL.RDLUF_MIXS2.DIM = 28
_C.MODEL.RDLUF_MIXS2.OUT_DIM = 28
_C.MODEL.RDLUF_MIXS2.STAGE_INTERACTION = True 
_C.MODEL.RDLUF_MIXS2.BLOCK_INTERACTION = True 
_C.MODEL.RDLUF_MIXS2.SPECTRAL_BRANCH = True 
_C.MODEL.RDLUF_MIXS2.SPATIAL_BRANCH = True 
_C.MODEL.RDLUF_MIXS2.SPECTRAL_INTERACTION = True 
_C.MODEL.RDLUF_MIXS2.SPATIAL_INTERACTION = True 
_C.MODEL.RDLUF_MIXS2.FFN_NAME = "Gated_Dconv_FeedForward" 
_C.MODEL.RDLUF_MIXS2.FFN_EXPAND = 2.66 
_C.MODEL.RDLUF_MIXS2.DW_EXPAND = 1
_C.MODEL.RDLUF_MIXS2.LAYERNORM_TYPE = "BiasFree" 

# Lambda_Net
_C.MODEL.LAMBDA_NET = CN()
_C.MODEL.LAMBDA_NET.IN_CH = 28
_C.MODEL.LAMBDA_NET.OUT_CH = 28

# DNU
_C.MODEL.DNU = CN()
_C.MODEL.DNU.N_CHANNELS = 28
_C.MODEL.DNU.L = 64
_C.MODEL.DNU.K = 11

# DERNN_LNLT
_C.MODEL.DERNN_LNLT = CN()
_C.MODEL.DERNN_LNLT.LOCAL = True
_C.MODEL.DERNN_LNLT.NON_LOCAL = True
_C.MODEL.DERNN_LNLT.IN_DIM = 28
_C.MODEL.DERNN_LNLT.OUT_DIM = 28
_C.MODEL.DERNN_LNLT.DIM = 28
_C.MODEL.DERNN_LNLT.WINDOW_SIZE = [8, 8]
_C.MODEL.DERNN_LNLT.WINDOW_NUM = [8, 8]
_C.MODEL.DERNN_LNLT.NUM_BLOCKS = [1, 1, 1, 1, 1]
_C.MODEL.DERNN_LNLT.FFN_NAME = "Gated_Dconv_FeedForward"
_C.MODEL.DERNN_LNLT.FFN_EXPAND = 2.66
_C.MODEL.DERNN_LNLT.LAYERNORM_TYPE = "WithBias"
_C.MODEL.DERNN_LNLT.STAGES = 5
_C.MODEL.DERNN_LNLT.SHARE_PARAMS = True
_C.MODEL.DERNN_LNLT.WITH_DL = True
_C.MODEL.DERNN_LNLT.WITH_MU = True
_C.MODEL.DERNN_LNLT.WITH_NOISE_LEVEL = True

# ADRNN_XST
_C.MODEL.ADRNN_XST = CN()
_C.MODEL.ADRNN_XST.IN_DIM = 28
_C.MODEL.ADRNN_XST.OUT_DIM = 28
_C.MODEL.ADRNN_XST.DIM = 28
_C.MODEL.ADRNN_XST.NUM_BLOCKS = [1, 1, 1, 1, 1]
_C.MODEL.ADRNN_XST.S_MSAB_NUM_BLOCKS = 1
_C.MODEL.ADRNN_XST.X_MSAB_NUM_BLOCKS = 1
_C.MODEL.ADRNN_XST.FFN_NAME = "Gated_Dconv_FeedForward"
_C.MODEL.ADRNN_XST.FFN_EXPAND = 2.66
_C.MODEL.ADRNN_XST.LAYERNORM_TYPE = "WithBias"
_C.MODEL.ADRNN_XST.STAGES = 5
_C.MODEL.ADRNN_XST.SHARE_PARAMS = True

# EMA
_C.MODEL.EMA = CN()
_C.MODEL.EMA.ENABLE = True
_C.MODEL.EMA.DECAY = 0.999


# OPTIMIZER
_C.OPTIMIZER = CN()
_C.OPTIMIZER.MAX_EPOCH = 300
_C.OPTIMIZER.LR = 2e-4
_C.OPTIMIZER.GRAD_CLIP = True


# SCHEDULER
_C.SCHEDULER = CN()
_C.SCHEDULER.TYPE = ""
_C.SCHEDULER.STEP = "step"


_C.LOSSES = CN()
_C.LOSSES.L1_LOSS = True
_C.LOSSES.L2_LOSS = False
_C.LOSSES.TV_LOSS = False